### ISSUE TITLE
Config files are incredibly vauge

### ISSUE THREAD

**Issue by slushie0** [IkeVoodoo/LSSMP#213]
For example:

```
elimination:
  environmentStealsHearts: true
  environmentHealthScale: 1.0
  healthScale: 1.0
  maxHearts: 20.0
  useMaxHealth: true
  minHearts: 5.0
  useMinHealth: false
  defaultHearts: 10.0
  useReviveHearts: true
  reviveHearts: 10.0
  totemWorksInInventory: false
  alwaysDropHearts: false
  fullInventoryHeartDrop: true
  allowedWorlds:
```

What do half of these mean? maxHearts is probably the most hearts you can get, but then what is minHearts? what is useMinHealth, or healthScale? Or environmentStealsHearts? I'm glad it has all of these features, but I don't even know what half of them mean, so I can't configure anything!
